module.exports = {
  data: {
    modata:[
      {
        name:'线路走向方案',
        error:13,
        errordata:[
          {
            name:'线路走向方案选择原则',
            error:4,
            subdata:[
              {
                name:'线路走向方案选择原则',
                data:[
                  {
                      name:'弹性敷衍',
                      text:'该问题描述'
                    },{
                      name:'弹性敷衍2',
                      text:'该问题描述2'
                    },{
                      name:'弹性敷衍3',
                      text:'该问题描述3'
                    }
                ],
              }
            ]
          },{
            name:'线路走向方案',
            error:4,
            subdata:[
              {
                name:'线路走向方案',
                data:[],
              }
            ]
          },{
            name:'线路走向方案比选',
            error:4,
            subdata:[
              {
                name:'线路走向方案比选',
                data:[],
              }
            ]
          }
        ]
      },{
        name:'线路走向推荐方案',
        error:0,
        errordata:[
          {
            name:'推荐线路方案-共4项',
            error:4,
            subdata:[
                {
                  name:'推荐线路走向',
                  data:[
                    {}
                  ],
                },{
                  name:'推荐线路难点段描述',
                  data:[
                    {
                      name:'弹性敷衍',
                      text:'该问题描述'
                    },{
                      name:'弹性敷衍2',
                      text:'该问题描述2'
                    },{
                      name:'弹性敷衍3',
                      text:'该问题描述3'
                    }
                  ]
                }
            ]
          },{
            name:'沿线自然条件及社会条件-共3项',
            error:4,
            subdata:[
              {
                name:'沿线自然条件及社会条件',
                data:[],
              }
            ]
          }
        ]
      },,{
        name:'管道敷设',
        error:13,
        errordata:[
          {
            name:'管道敷设原则-共4项',
            error:4,
            subdata:[
                {
                  name:'管道敷设原则',
                  data:[],
                }
            ]
          },{
            name:'一般地段管道敷设-共3项',
            error:4,
            subdata:[
              {
                name:'一般地段管道敷设',
                data:[],
              }
            ]
          },{
            name:'特殊地段管道敷设-共3项',
            error:4,
            subdata:[
              {
                name:'特殊地段管道敷设',
                data:[],
              }
            ]
          }
        ]
      },{
        name:'穿跨越工程',
        error:13,
        errordata:[
          {
            name:'穿跨越工程概况-共4项',
            error:4,
            subdata:[
                {
                  name:'穿跨越工程概况',
                  data:[],
                }
            ]
          },{
            name:'穿跨越水域、冲沟-共3项',
            error:4,
            subdata:[
              {
                name:'穿跨越水域、冲沟',
                data:[],
              }
            ]
          },{
            name:'穿越山岭-共3项',
            error:4,
            subdata:[
              {
                name:'穿越山岭',
                data:[],
              }
            ]
          },{
            name:'公路和铁路穿越-共3项',
            error:4,
            subdata:[
              {
                name:'公路和铁路穿越',
                data:[],
              }
            ]
          },{
            name:'穿越施工方案-共3项',
            error:4,
            subdata:[
              {
                name:'穿越施工方案',
                data:[],
              }
            ]
          },{
            name:'穿跨越管段安全防范设计-共3项',
            error:4,
            subdata:[
              {
                name:'穿跨越管段安全防范设计',
                data:[],
              }
            ]
          }
        ]
      },{
        name:'控制性工程',
        error:13,
        errordata:[
          {
            name:'控制性工程统计表',
            error:4,
            subdata:[
                {
                  name:'控制性工程统计表',
                  data:[],
                }
            ]
          },{
            name:'各控制性工程主要工程量-共3项',
            error:4,
            subdata:[
              {
                name:'各控制性工程主要工程量',
                data:[],
              }
            ]
          }
        ]
      },{
        name:'线路附属设施',
        error:13,
        errordata:[
          {
            name:'线路截断阀室',
            error:4,
            subdata:[
                {
                  name:'线路截断阀室设置目的和原则',
                  data:[],
                },{
                  name:'控制方式和数量',
                  data:[],
                },{
                  name:'分布统计',
                  data:[],
                },{
                  name:'线路截断阀室设置位置',
                  data:[],
                }
            ]
          },{
            name:'管道标志桩（测试桩）、警示牌及特殊安全保护设施-共3项',
            error:4,
            subdata:[
              {
                name:'管道标志桩（测试桩）、警示牌及特殊安全保护设施',
                data:[],
              }
            ]
          },{
            name:'水工保护和水土保持-共3项',
            error:4,
            subdata:[
              {
                name:'水工保护和水土保持',
                data:[],
              }
            ]
          },{
            name:'固定墩设置-共3项',
            error:4,
            subdata:[
              {
                name:'固定墩设置',
                data:[],
              }
            ]
          },{
            name:'道路工程-共3项',
            error:4,
            subdata:[
              {
                name:'伴行道路（新建）',
                data:[],
              },{
                name:'伴行道路（改、扩建）',
                data:[],
              },{
                name:'施工道路',
                data:[],
              }
            ]
          },{
            name:'线路主要工程量-共3项',
            error:4,
            subdata:[
              {
                name:'线路主要工程量',
                data:[],
              }
            ]
          }
        ]
      }
    ]
  }
}